- name: Creating an administrative user account
  user:
    name: "{{ USER_ACCOUNT }}"
    group: ansible
    shell: /bin/bash

- name: Adding the SSH keypair to the user's authorized_keys file.
  authorized_key:
    user: "{{ USER_ACCOUNT }}"
    key: "{{ lookup('file', '{{ SSH_KEY }}.pub') }}"
