---
- fail:
    msg: "You have not exported all of the required environment variables to configure MSMTP"
  when: >
    VAR_MSMTP_SERVER == "" or
    VAR_MSMTP_PORT == "" or
    VAR_MSMTP_EMAIL == "" or
    VAR_MSMTP_PASSWORD == ""

- name: Installing an email and smtp relay client
  apt: 
    state: present
    name:
    - bsd-mailx
    - msmtp
    - msmtp-mta

- name: Configuring msmtp
  blockinfile:
    path: /etc/msmtprc
    create: yes
    block: |
      account default
      auth on
      host {{ VAR_MSMTP_SERVER }}
      port {{ VAR_MSMTP_PORT }}
      tls on
      tls_starttls on
      user {{ VAR_MSMTP_EMAIL }}
      password {{ VAR_MSMTP_PASSWORD }}
      from proxmox
      maildomain {{ inventory_hostname }}
      syslog LOG_MAIL

- name: Disabling TLS because you're naughty
  become: yes
  replace:
      path: /etc/msmtprc
      regexp: 'tls on'
      replace: 'tls off'
  when: VAR_MSMTP_TLS == "false"
