---
- hosts: proxmox
  become: true
  gather_facts: false
  tasks:
    - import_role: 
        name: Configure_Proxmox
      vars:     
        # Configure Tasks
        CONFIGURE_REPOSITORIES: "{{ lookup('env', 'TKS_BP_T_CONFIGURE_REPOSITORIES') | default('false') }}"
        CONFIGURE_UNATTENDED_UPGRADES: "{{ lookup('env', 'TKS_BP_T_CONFIGURE_UNATTENDED_UPGRADES') | default('false') }}"
        # CONFIGURE_ZED: "{{ lookup('env', 'TKS_BP_T_CONFIGURE_ZED') }}"
        #
        #
        # Install Tasks
        INSTALL_PACKAGES: "{{ lookup('env', 'TKS_BP_T_INSTALL_PACKAGES') }}"
        # INSTALL_SANOID: "{{ lookup('env', 'TKS_BP_T_INSTALL_SANOID') }}" 
        INSTALL_MSMTP: "{{ lookup('env', 'TKS_BP_T_INSTALL_MSMTP') }}"    
        # INSTALL_ZSH: "{{ lookup('env', 'TKS_BP_T_INSTALL_ZSH') }}"   
        #
        #
        # MSMTP Variables
        VAR_MSMTP_SERVER: "{{ lookup('env', 'TKS_BP_V_MSMTP_SERVER') | default('smtp.gmail.com') }}"
        VAR_MSMTP_PORT: "{{ lookup('env', 'TKS_BP_V_MSMTP_PORT') | default('587') }}"
        VAR_MSMTP_TLS: "{{ lookup('env', 'TKS_BP_V_MSMTP_TLS') | default('true') )}}"
        VAR_MSMTP_EMAIL: "{{ lookup('env', 'TKS_BP_V_MSMTP_EMAIL') }}"
        VAR_MSMTP_PASSWORD: "{{ lookup('env', 'TKS_BP_V_MSMTP_PASSWORD') }}"
        #
        #
        # Unattended Upgrades Variables
        VAR_UPGRADES_NOTIFY: "{{ lookup('env', 'TKS_BP_V_UPGRADES_NOTIFY') | default('true') }}"
        VAR_UPGRADES_NOTIFY_ON_ERROR: "{{ lookup('env', 'TKS_BP_V_UPGRADES_NOTIFY_ON_ERROR') | default('false') }}"
        VAR_UPGRADES_EMAIL: "{{ lookup('env', 'TKS_BP_V_UPGRADES_EMAIL') }}"
        VAR_UPGRADES_UNUSED_DEP: "{{ lookup('env', 'TKS_BP_V_UPGRADES_UNUSED_DEP') | default('false') }}"
        VAR_UPGRADES_UNUSED_K_PAC: "{{ lookup('env', 'TKS_BP_V_UPGRADES_UNUSED_K_PAC') | default('false') }}"
        VAR_UPGRADES_AUTO_REBOOT: "{{ lookup('env', 'TKS_BP_V_UPGRADES_AUTO_REBOOT') | default('false') }}"
        VAR_UPGRADES_AUTO_REBOOT_TIME: "{{ lookup('env', 'TKS_BP_V_UPGRADES_AUTO_REBOOT_TIME') | default('03:00') }}"
        VAR_UPGRADES_ON_SHUTDOWN: "{{ lookup('env', 'TKS_BP_V_UPGRADES_ON_SHUTDOWN') | default('true') }}"
        VAR_UPGRADES_LOG_SYSLOG: "{{ lookup('env', 'TKS_BP_V_UPGRADES_LOG_SYSLOG') | default('true') }}"
